import { ROLES } from './roles';

export const PERMISSIONS = {
  SUPER_ADMIN: [ROLES.SUPER_ADMIN],
  SUB_ADMIN: [ROLES.SUB_ADMIN, ROLES.SUPER_ADMIN],
  COMPANY_ADMIN: [ROLES.COMPANY_ADMIN, ROLES.SUB_ADMIN, ROLES.SUPER_ADMIN],
  HR_MANAGER: [ROLES.HR_MANAGER, ROLES.COMPANY_ADMIN, ROLES.SUB_ADMIN, ROLES.SUPER_ADMIN],
  HR_EXECUTIVE: [ROLES.HR_EXECUTIVE, ROLES.COMPANY_ADMIN, ROLES.SUB_ADMIN, ROLES.SUPER_ADMIN],
  MANAGER: [ROLES.MANAGER, ROLES.HR_MANAGER, ROLES.HR_EXECUTIVE, ROLES.COMPANY_ADMIN, ROLES.SUB_ADMIN, ROLES.SUPER_ADMIN],
  EMPLOYEE: [ROLES.EMPLOYEE, ROLES.HR_MANAGER, ROLES.HR_EXECUTIVE, ROLES.COMPANY_ADMIN, ROLES.SUB_ADMIN, ROLES.SUPER_ADMIN],
};

export function canAccessRole(currentRole, allowedRoles = []) {
  return allowedRoles.includes(currentRole);
}
