import { ROLES } from './roles';

export const PERMISSIONS = {
  SUPER_ADMIN: [ROLES.SUPER_ADMIN],
  SUB_ADMIN: [ROLES.SUB_ADMIN, ROLES.SUPER_ADMIN],
  COMPANY_ADMIN: [ROLES.COMPANY_ADMIN, ROLES.SUB_ADMIN, ROLES.SUPER_ADMIN],
  HR: [ROLES.HR, ROLES.COMPANY_ADMIN, ROLES.SUB_ADMIN, ROLES.SUPER_ADMIN],
  MANAGER: [ROLES.MANAGER, ROLES.HR, ROLES.COMPANY_ADMIN, ROLES.SUB_ADMIN, ROLES.SUPER_ADMIN],
  EMPLOYEE: [ROLES.EMPLOYEE, ROLES.HR, ROLES.COMPANY_ADMIN, ROLES.SUB_ADMIN, ROLES.SUPER_ADMIN],
};

export function canAccessRole(currentRole, allowedRoles = []) {
  return allowedRoles.includes(currentRole);
}
